# Generated by Django 4.2.2 on 2023-06-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_no_of_gests_alter_menu_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_gests',
            new_name='num_of_guests',
        ),
    ]
